[package]
name = "doteur_core"
version = "0.5.1"
authors = ["nag763 <loic.labeye@tutanota.de>"]
edition = "2018"
license = "MIT"
homepage = "https://nag763.github.io/doteur"
description = "Libraries for doteur"
readme = "../README.md"
repository = "https://github.com/nag763/doteur/"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
log = "0.4.14"
itertools = "0.10.3"
mysql = { version="21.0.2", optional=true}
rusqlite = { version="0.26.3", optional=true}

[features]
mysql_addons = ["mysql"]
sqlite_addons = ["rusqlite"]
