title: Doteur wiki
email: loic.labeye@tutanota.de
description: >- # this means to ignore newlines until "baseurl:"
        Doteur is an awesome tool to transform your SQL schemas into DOT files usable by GraphViz. It will help you to make good looking schemas in few seconds.
baseurl: "/doteur" # the subpath of your site, e.g. /blog
url: "https://nag763.github.io"
github_username:  nag763
github_repo: doteur

markdown: kramdown
theme: just-the-docs
url: https://nag763.github.io
domain: nag763.github.io
logo: "./assets/logo.png"
aux_links:
  "GitHub repository":
          - "https://github.com/nag763/doteur"
  "ðŸ†• Live demo":
          - "https://nag763.github.io/doteur/live"
heading_anchors: true
footer_content: "Copyright &copy; 2021-2024 LABEYE LoÃ¯c. Distributed by an <a href=\"https://github.com/nag763/doteur/LICENCE.MD\">MIT Licence</a>"
last_edit_timestamp: true
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor